### ISSUE TITLE
处理{{ }}中绑定内容的问题

### ISSUE THREAD

**Issue by MrJumpShot** [canfoo/self-vue#7]
一个小bug，在compile.js中处理{{name}}时正则匹配后trim一下，不然没法处理{{ name }}这样的情况。谢谢。

**Comment by canfoo** [comment]
ok ，感谢指出，已经修正，不过我这边是直接优化原有正则进行筛选，即改成：`/\{\{\s*(.*?)\s*\}\}/`
@MrJumpShot

**Comment by MrJumpShot** [comment]
从你的代码里学到了很多，感谢
